### ISSUE TITLE
Provide guidance on stdin/filepath handling with daemon

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku-daemon#3]
Certain commands require input on stdin and/or a specific path on disk. I'm not sure _how_ we want to handle this, though ideally we do this transparently to the user.

**Comment by joshmcrae** [comment]
I think this could be achieved by providing the paths as regular arguments and prefixing them with a special character depending on whether they are to be piped or 'expanded' to actual names.

```
certs:add my-app @server.crt @server.key
certs:add my-app <cert-key.tar
```

Because the client may be running from a container it makes little sense to use absolute paths. The paths should be relative to a special namespace on the host (i.e. `/tmp/dokku-daemon`) that can be mounted to a container. The example above would therefore expand `cert-key.tar` to `/tmp/dokku-daemon/cert-key.tar`.

If a special namespace is used, we might want to remove the environment variables `DOKKU_SOCK_PATH/DOKKU_LOCK_PATH`.

**Comment by josegonzalez** [comment]
If I was mounting the socket into another container and using it from some web api, how would the web api know where to write the file? Env var of a mounted volume?

**Comment by joshmcrae** [comment]
Yes, you would provide the location of the mounted namespace as an env var.

The purpose of the namespace is that the socket and any files that need to be written by the API or read by the daemon will be located in the one place. If the web API knows how to access the socket, it knows where to write files (like user uploads).

**Comment by josegonzalez** [comment]
Are there any cases where we might use a special `@` symbol as a prefix to something?

Why would we want to remove those env vars?

(Also, would be nice to default to `/var/run/dokku-daemon/dokku-daemon.sock` for the socket path...).

**Comment by joshmcrae** [comment]
The `@` would expand to a literal filepath whereas `<` would have the effect of piping from a file with that name. Are you concerned that `@` might already be a valid prefix for an argument to the `dokku` command?

Deleting those env vars would simply force all of the relevant files into a single directory (under the namespace). I thought this might make things easier when mounting the files in a container. No real benefits here otherwise.

I agree that the socket should go under `/var/run/dokku-daemon`. The lock file should also go under `/var/lock/dokku-daemon`.

**Comment by josegonzalez** [comment]
Okay I think we are in agreement here. Want to take a stab at this? :D

> I can't think of any other feature we might want for the dokku-daemon, but if you can think of anything, now is the time, as it would be nice to start writing an api on top of the daemon...
